patientApp/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template
# from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'entry.views.HomePage'),
    (r'^register/$', 'entry.views.PatientRegistration'),
    (r'^login/$', 'entry.views.LoginRequest'),
    (r'^logout/$', 'entry.views.LogoutRequest'),
    (r'^profile/$', 'entry.views.Profile'),
    (r'^entry/$', 'entry.views.AddEntry'),
    (r'^hello/$', 'entry.views.hello'),
    (r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^resetpassword/$', 'django.contrib.auth.views.password_reset'),
    (r'^reset/(?P<uidb36>[0-9A-Za-z]*)-(?P<token>.*)/$', 'django.contrib.auth.views.password_reset_confirm'),
    (r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
    (r'^code/$', direct_to_template, {'template': 'code.html', 'extra_context': {'showDirect': True}}),

    url(r'^admin/', include(admin.site.urls)),
)

entry/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from Crypto.Cipher import Blowfish
import binascii
import datetime

GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
)

class Patient(models.Model):
    user = models.OneToOneField(User) # import User
    name = models.CharField(max_length=100)
    birthday = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    email = models.EmailField(blank=True, verbose_name='e-mail')
    cell = models.CharField(max_length=10, blank=True, verbose_name='cell #')
    created = models.DateField(editable=False)
    updated = models.DateTimeField(editable=False)

    def save(self, *args, **kwargs):
        if not 'force_insert' in kwargs:
            kwargs['force_insert'] = False
        if not 'force_update' in kwargs:
            kwargs['force_update'] = False
        if not self.id:
            self.created = datetime.date.today()
        self.updated = datetime.datetime.today()
        super(Patient, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

class Entry(models.Model):
    entry = models.CharField(max_length=15)
    description = models.TextField(blank=True)
    patient = models.ForeignKey('Patient')
    created = models.DateField(editable=False)

    def _get_desc(self):
        enc_obj = Blowfish.new( settings.SECRET_KEY )
        return u"%s" % enc_obj.decrypt( binascii.a2b_hex(self.description) ).rstrip()

    def _set_desc(self, desc_value):
        enc_obj = Blowfish.new( settings.SECRET_KEY )
        repeat = 8 - (len( desc_value ) % 8)
        desc_value = desc_value + " " * repeat
        self.description = binascii.b2a_hex(enc_obj.encrypt( desc_value ))

    desc = property(_get_desc, _set_desc)

    def save(self, *args, **kwargs):
        if not 'force_insert' in kwargs:
            kwargs['force_insert'] = False
        if not 'force_update' in kwargs:
            kwargs['force_update'] = False
        if not self.id:
            self.created = datetime.date.today()
        self.updated = datetime.datetime.today()
        super(Entry, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s (%s)' % (self.entry, self.desc)
        

entry/forms.py
from django import forms
from django.forms import ModelForm
from entry.models import Patient, Entry
from django.contrib.auth.models import User

class RegistrationForm(ModelForm):
    name                   = forms.CharField(label=(u'User Name'))
    email                   = forms.EmailField(label=(u'Email Address'))
    password             = forms.CharField(label=(u'Password'), widget=forms.PasswordInput(render_value=False))
    password1           = forms.CharField(label=(u'Verify Password'), widget=forms.PasswordInput(render_value=False))
    
    class Meta:
        model = Patient
        exclude = ('user',)

    def clean_name(self):
        name = self.cleaned_data['name']
        try:
            User.objects.get(username=name)
        except User.DoesNotExist:
            return name
        raise forms.ValidationError('That username is already take, please select another name')
        
    def clean(self):
        if self.cleaned_data.get('password') != self.cleaned_data.get('password1'):
            raise forms.ValidationError("The passwords did not match. Please try again.")
        return self.cleaned_data

class EntryForm(ModelForm):
    entry                    = forms.CharField(label=(u'Entry'))
    desc                     =  forms.CharField(label=(u'Description'), widget=forms.Textarea)

    class Meta:
        model = Entry
        exclude = ('patient',)

class LoginForm(forms.Form):
    name                   = forms.CharField(label=(u'User Name'))
    password             = forms.CharField(label=(u'Password'), widget=forms.PasswordInput(render_value=False))

entry/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render_to_response
from entry.models import Patient, Entry
from entry.forms import RegistrationForm, LoginForm, EntryForm
from urllib import urlencode
from urllib2 import urlopen

from tropo import Tropo, Session, Message
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def hello(request):
    try:
        t = Tropo()
                
        session = Session(request.body)
        if('parameters' in dir(session)):
            print('Message request')

            t.call(to="+"+session.parameters['to'].strip(), network = "SMS")
            json = t.say(session.parameters['msg'])
            json = t.RenderJson(json)
            return HttpResponse(json)

        else :

            msg = request.POST.get('msg', '')
            s = Session(request.body)
            cell = s.fromaddress['id']

            # lookup patient with this cell #
            if cell[0]=='1':   # trim leading 1 in cell # if there
                cell = cell[1:]
            print('Cell #%s' % cell)
            p = Patient.objects.filter(cell=cell)   # all patients with this cell #
            if p.exists():                                    # if cell # found then create new entry
                if p.count()>1:
                    print('WARNING: Multiple patients with cell # %s' % cell)
                parent = p[0]  # assume first 
                entry = Entry(patient=parent, entry=msg)
                entry.save()
                if msg.find('CODE')>-1:
                    json = t.say("Congratulations " + parent.name + " your code qualified you for a prize!")            
                else:
                    json = t.say("Entry saved, thank you " + parent.name)
            else:                                               # if cell # NOT found then notify
                json = t.say("Could not find patient with cell # " + cell)

            json = t.RenderJson(json)
            return HttpResponse(json)

    except Exception, err:
        print('ERROR: %s\n' % str(err))



def HomePage(request):
    context = {}
    return render_to_response('index.html', context, context_instance=RequestContext(request))
    

def PatientRegistration(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/profile/')
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(username=form.cleaned_data['name'], email = form.cleaned_data['email'], password = form.cleaned_data['password'])
            user.save()
            patient = Patient(user=user, name=form.cleaned_data['name'], birthday=form.cleaned_data['birthday'], gender = form.cleaned_data['gender'], email = form.cleaned_data['email'], cell = form.cleaned_data['cell'])
            patient.save()

            # text patient if cell # provided
            if len(patient.cell)==10:

                try:
                    send_message("1"+patient.cell, "Thank you for registering.")
                    print "Registration confirmation sent"
                except Exception, err:
                    print('ERROR: %s\n' % str(err))

            return HttpResponseRedirect('/profile/')

        else:   # form is not valid
#            print form.errors
            return render_to_response('register.html', {'form':form}, context_instance=RequestContext(request))
    
    else:
        ''' user is not submitting the form '''
        form = RegistrationForm()
        context = {'form': form}
        return render_to_response('register.html', context, context_instance=RequestContext(request))

@login_required
def Profile(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    patient = request.user.get_profile
    context = {'patient': patient}
    return render_to_response('profile.html', context, context_instance=RequestContext(request))


def LoginRequest(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/profile/')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            password = form.cleaned_data['password']
            print "authenticating user: %s" % name
            user = authenticate(username=name, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/profile/')
            else:
                
                return render_to_response('login.html', {'form':form}, context_instance=RequestContext(request))
        else:
            return render_to_response('login.html', {'form':form}, context_instance=RequestContext(request))
        
    else:
        form = LoginForm()
        context = {'form': form}
        return render_to_response('login.html', context, context_instance=RequestContext(request))

def LogoutRequest(request):
    logout(request)
    return HttpResponseRedirect('/')
        
def AddEntry(request):
    if request.user.is_authenticated():
        if request.method == 'POST':
            form = EntryForm(request.POST)
            if form.is_valid():
                parent = request.user.get_profile()
                entry = Entry(patient=parent, entry=form.cleaned_data['entry'], desc=form.cleaned_data['desc'])
                entry.save()
                if form.cleaned_data['entry'].find('CODE')>-1:
                    return HttpResponseRedirect('/code/')
                else:
                    return HttpResponseRedirect('/profile/')
            else:
                print form.errors
                return render_to_response('entry.html', {'form':form}, context_instance=RequestContext(request))
        else:
            ''' user is not submitting the form '''
            form = EntryForm()
            context = {'form': form}
            return render_to_response('entry.html', context, context_instance=RequestContext(request))
    else:
        pass


def send_message(cell, msg):
    base_url = 'http://api.tropo.com/1.0/sessions'
    token = '13bed2b0b149a5449342d27e3728470c308535c1c2033349cc1735d293bcd3dfbc64601eab5934e7c45c52f1'      
    action = 'create'
    number  = cell
    message = msg
        
    params = urlencode([('action', action), ('token', token), ('to', number), ('msg', message), ('outgoing', True)])
    urlopen('%s?%s' % (base_url, params))

patientApp/templates/base.html
<html>
<head>
    <link rel='stylesheet' type='text/css' href='/static/css/patientApp.css' />
    {% block extrahead %}{% endblock %}
</head>
<body>
<div id='pageContainer'>
    <div id="nav_top_right">
        {% if user.is_authenticated %}<p><small><a href='/logout/'>Logout</a></small></p>{% else %}<p><small><a href='/login/'>Login</a></small></p>
        {% endif %}
    </div>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

patientApp/templates/code.html
{% extends 'base.html' %}
{% block content %}
    <div id='code_screen'>
<img id="logo" src="/static/images/aLogo.jpg" width="100" height="100" border="0" alt="Logo" />
    </div>
    <h1>
    Congratulations!
    </h1>
    <h2>
    The code you entered entitles you to prizes!
    </h2>
{% endblock %}

patientApp/templates/entry.html
{% extends "base.html" %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
{% if form.errors %}<p>Please correct the following fields:</p>{% endif %}
<div class="register_div">
    {% if form.entry.errors %}<p class="error">{{ form.entry.errors }}</p>{% endif %}
    <p><label for="entry" {% if form.entry.errors %} class="error">{% endif %}>Entry:</label></p>
    <p>{{ form.entry }}</p>
</div>
<div class="register_div">
    {% if form.desc.errors %}<p class="error">{{ form.desc.errors }}</p>{% endif %}
    <p><label for="desc" {% if form.desc.errors %} class="error">{% endif %}>Description:</label></p>
    <p>{{ form.desc }}</p>
</div>
<p><input type="submit" alt="register"/></p>
</form>
{% endblock %}

patientApp/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div id='home_copy'>
        <h2>Patient Portal</h2>
    </div>
    <img id="logo" src="/static/images/testKit.jpg" width="100" height="100" border="0" alt="Logo" />

{% endblock %}

patientApp/templates/login.html
{% extends "base.html" %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
{% if form.errors %}<p>Please correct the following fields:</p>{% endif %}

<div class="login_div">

<TABLE BORDER="0">
<TR>
    <TD>
    {% if form.name.errors %}<p class="error">{{ form.name.errors }}</p>{% endif %}
    <p><label for="name" {% if form.name.errors %} class="error">{% endif %}>Username:</label></p>
    </TD>
    <TD><p>{{ form.name }}</p></TD>
</TR>

<TR>
    <TD>
    {% if form.password.errors %}<p class="error">{{ form.password.errors }}</p>{% endif %}
    <p><label for="password" {% if form.password.errors %} class="error">{% endif %}>Password:</label></p>
    </TD>
    <TD><p>{{ form.password }}</p></TD>
</TR>

</div>

</TABLE>

<p><input type="submit" alt="login"/></p>
</form>
<p>Need an account? <a href='/register/'>Register</a></p>
<p>Forgot your password? <a href='/resetpassword/'>Reset it</a></p>


{% endblock %}

patientApp/templates/profile.html
{% extends 'base.html' %}
{% block content %}
    <p>Name: {{patient.name}}</p>
    <p>Birthday: {{patient.birthday }}</p>
<br>
    <div id='entrylist'>
        {% for entry in patient.entry_set.all %}
        <p>{{ entry }}</p>
        {% endfor %}
    </div>

<a href='/entry/'>Add Entry</a>
{% endblock %}

patientApp/templates/register.html
{% extends "base.html" %}
{% block extrahead %}
    <link rel="stylesheet" href="/static/css/datepicker.css" type="text/css" media="screen"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.js" type="text/javascript"></script>
    <script>
	$(function() {
		$( "#id_birthday" ).datepicker();
	});
	</script>
{% endblock %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
{% if form.errors %}<p>Please correct the following fields:</p>{% endif %}

<TABLE BORDER="0">
<TR>
    <TD>
    {% if form.name.errors %}<p class="error">{{ form.name.errors }}</p>{% endif %}    
    <p><label for="name" {% if form.name.errors %} class="error">{% endif %}>Username:</label></p>
    </TD>
    <TD><p>{{ form.name }}</p></TD>
</TR>

<TR>
    <TD>
    {% if form.email.errors %}<p class="error">{{ form.email.errors }}</p>{% endif %}
    <p><label for="email" {% if form.email.errors %} class="error">{% endif %}>Email:</label></p>    
    </TD>
    <TD><p>{{ form.email }}</p></TD>
</TR>

<TR>
    <TD>
    {% if form.password.errors %}<p class="error">{{ form.password.errors }}</p>{% endif %}
    <p><label for="password" {% if form.password.errors %} class="error">{% endif %}>Password:</label></p>
    </TD>
    <TD><p>{{ form.password }}</p></TD>
</TR>

<TR>
    <TD>
    {% if form.password1.errors %}<p class="error">{{ form.password1.errors }}</p>{% endif %}
    <p><label for="password1" {% if form.password1.errors %} class="error">{% endif %}>Verify Password:</label></p>
    </TD>
    <TD><p>{{ form.password1 }}</p></TD>
</TR>


<TR>
    <TD>
    {% if form.birthday.errors %}<p class="error">{{ form.birthday.errors }}</p>{% endif %}
    <p><label for="birthday" {% if form.birthday.errors %} class="error">{% endif %}>Birthday:</label></p>
    </TD>
    <TD><p>{{ form.birthday }}</p></TD>
</TR>

<TR>
    <TD>
    {% if form.gender.errors %}<p class="error">{{ form.gender.errors }}</p>{% endif %}
    <p><label for="gender" {% if form.gender.errors %} class="error">{% endif %}>Gender:</label></p>
    </TD>
    <TD><p>{{ form.gender }}</p></TD>
</TR>

<TR>
    <TD>
    {% if form.cell.errors %}<p class="error">{{ form.cell.errors }}</p>{% endif %}
    <p><label for="cell" {% if form.cell.errors %} class="error">{% endif %}>Cell #:</label></p>
    </TD>
    <TD><p>{{ form.cell }}</p></TD>
</TR>

</TABLE>

<p><input type="submit" value="Register" alt="register"/></p>
</form>
{% endblock %}